# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/morbo/CLionProjects/prologix_emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/morbo/CLionProjects/prologix_emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/local/bin/cpack --config ./CPackSourceConfig.cmake /Users/morbo/CLionProjects/prologix_emulator/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/morbo/CLionProjects/prologix_emulator/CMakeFiles /Users/morbo/CLionProjects/prologix_emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/morbo/CLionProjects/prologix_emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prologix_emulator

# Build rule for target.
prologix_emulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 prologix_emulator
.PHONY : prologix_emulator

# fast build rule for target.
prologix_emulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/build
.PHONY : prologix_emulator/fast

#=============================================================================
# Target rules for targets named boost_container

# Build rule for target.
boost_container: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_container
.PHONY : boost_container

# fast build rule for target.
boost_container/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/container/CMakeFiles/boost_container.dir/build.make _deps/boost-build/libs/container/CMakeFiles/boost_container.dir/build
.PHONY : boost_container/fast

#=============================================================================
# Target rules for targets named boost_context

# Build rule for target.
boost_context: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_context
.PHONY : boost_context

# fast build rule for target.
boost_context/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/context/CMakeFiles/boost_context.dir/build.make _deps/boost-build/libs/context/CMakeFiles/boost_context.dir/build
.PHONY : boost_context/fast

#=============================================================================
# Target rules for targets named boost_coroutine

# Build rule for target.
boost_coroutine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_coroutine
.PHONY : boost_coroutine

# fast build rule for target.
boost_coroutine/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/coroutine/CMakeFiles/boost_coroutine.dir/build.make _deps/boost-build/libs/coroutine/CMakeFiles/boost_coroutine.dir/build
.PHONY : boost_coroutine/fast

#=============================================================================
# Target rules for targets named boost_date_time

# Build rule for target.
boost_date_time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_date_time
.PHONY : boost_date_time

# fast build rule for target.
boost_date_time/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/date_time/CMakeFiles/boost_date_time.dir/build.make _deps/boost-build/libs/date_time/CMakeFiles/boost_date_time.dir/build
.PHONY : boost_date_time/fast

#=============================================================================
# Target rules for targets named boost_exception

# Build rule for target.
boost_exception: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_exception
.PHONY : boost_exception

# fast build rule for target.
boost_exception/fast:
	$(MAKE) $(MAKESILENT) -f _deps/boost-build/libs/exception/CMakeFiles/boost_exception.dir/build.make _deps/boost-build/libs/exception/CMakeFiles/boost_exception.dir/build
.PHONY : boost_exception/fast

#=============================================================================
# Target rules for targets named screen

# Build rule for target.
screen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 screen
.PHONY : screen

# fast build rule for target.
screen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/ftxui-build/CMakeFiles/screen.dir/build.make _deps/ftxui-build/CMakeFiles/screen.dir/build
.PHONY : screen/fast

#=============================================================================
# Target rules for targets named dom

# Build rule for target.
dom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dom
.PHONY : dom

# fast build rule for target.
dom/fast:
	$(MAKE) $(MAKESILENT) -f _deps/ftxui-build/CMakeFiles/dom.dir/build.make _deps/ftxui-build/CMakeFiles/dom.dir/build
.PHONY : dom/fast

#=============================================================================
# Target rules for targets named component

# Build rule for target.
component: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 component
.PHONY : component

# fast build rule for target.
component/fast:
	$(MAKE) $(MAKESILENT) -f _deps/ftxui-build/CMakeFiles/component.dir/build.make _deps/ftxui-build/CMakeFiles/component.dir/build
.PHONY : component/fast

src/ClientList.o: src/ClientList.cpp.o
.PHONY : src/ClientList.o

# target to build an object file
src/ClientList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/ClientList.cpp.o
.PHONY : src/ClientList.cpp.o

src/ClientList.i: src/ClientList.cpp.i
.PHONY : src/ClientList.i

# target to preprocess a source file
src/ClientList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/ClientList.cpp.i
.PHONY : src/ClientList.cpp.i

src/ClientList.s: src/ClientList.cpp.s
.PHONY : src/ClientList.s

# target to generate assembly for a file
src/ClientList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/ClientList.cpp.s
.PHONY : src/ClientList.cpp.s

src/Commander.o: src/Commander.cpp.o
.PHONY : src/Commander.o

# target to build an object file
src/Commander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Commander.cpp.o
.PHONY : src/Commander.cpp.o

src/Commander.i: src/Commander.cpp.i
.PHONY : src/Commander.i

# target to preprocess a source file
src/Commander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Commander.cpp.i
.PHONY : src/Commander.cpp.i

src/Commander.s: src/Commander.cpp.s
.PHONY : src/Commander.s

# target to generate assembly for a file
src/Commander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Commander.cpp.s
.PHONY : src/Commander.cpp.s

src/Functions.o: src/Functions.cpp.o
.PHONY : src/Functions.o

# target to build an object file
src/Functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Functions.cpp.o
.PHONY : src/Functions.cpp.o

src/Functions.i: src/Functions.cpp.i
.PHONY : src/Functions.i

# target to preprocess a source file
src/Functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Functions.cpp.i
.PHONY : src/Functions.cpp.i

src/Functions.s: src/Functions.cpp.s
.PHONY : src/Functions.s

# target to generate assembly for a file
src/Functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Functions.cpp.s
.PHONY : src/Functions.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Responder.o: src/Responder.cpp.o
.PHONY : src/Responder.o

# target to build an object file
src/Responder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Responder.cpp.o
.PHONY : src/Responder.cpp.o

src/Responder.i: src/Responder.cpp.i
.PHONY : src/Responder.i

# target to preprocess a source file
src/Responder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Responder.cpp.i
.PHONY : src/Responder.cpp.i

src/Responder.s: src/Responder.cpp.s
.PHONY : src/Responder.s

# target to generate assembly for a file
src/Responder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/Responder.cpp.s
.PHONY : src/Responder.cpp.s

src/TCPServer.o: src/TCPServer.cpp.o
.PHONY : src/TCPServer.o

# target to build an object file
src/TCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/TCPServer.cpp.o
.PHONY : src/TCPServer.cpp.o

src/TCPServer.i: src/TCPServer.cpp.i
.PHONY : src/TCPServer.i

# target to preprocess a source file
src/TCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/TCPServer.cpp.i
.PHONY : src/TCPServer.cpp.i

src/TCPServer.s: src/TCPServer.cpp.s
.PHONY : src/TCPServer.s

# target to generate assembly for a file
src/TCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/TCPServer.cpp.s
.PHONY : src/TCPServer.cpp.s

src/TCPSession.o: src/TCPSession.cpp.o
.PHONY : src/TCPSession.o

# target to build an object file
src/TCPSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/TCPSession.cpp.o
.PHONY : src/TCPSession.cpp.o

src/TCPSession.i: src/TCPSession.cpp.i
.PHONY : src/TCPSession.i

# target to preprocess a source file
src/TCPSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/TCPSession.cpp.i
.PHONY : src/TCPSession.cpp.i

src/TCPSession.s: src/TCPSession.cpp.s
.PHONY : src/TCPSession.s

# target to generate assembly for a file
src/TCPSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/TCPSession.cpp.s
.PHONY : src/TCPSession.cpp.s

src/UDPServer.o: src/UDPServer.cpp.o
.PHONY : src/UDPServer.o

# target to build an object file
src/UDPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/UDPServer.cpp.o
.PHONY : src/UDPServer.cpp.o

src/UDPServer.i: src/UDPServer.cpp.i
.PHONY : src/UDPServer.i

# target to preprocess a source file
src/UDPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/UDPServer.cpp.i
.PHONY : src/UDPServer.cpp.i

src/UDPServer.s: src/UDPServer.cpp.s
.PHONY : src/UDPServer.s

# target to generate assembly for a file
src/UDPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/UDPServer.cpp.s
.PHONY : src/UDPServer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/prologix_emulator.dir/build.make CMakeFiles/prologix_emulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... boost_container"
	@echo "... boost_context"
	@echo "... boost_coroutine"
	@echo "... boost_date_time"
	@echo "... boost_exception"
	@echo "... component"
	@echo "... dom"
	@echo "... prologix_emulator"
	@echo "... screen"
	@echo "... src/ClientList.o"
	@echo "... src/ClientList.i"
	@echo "... src/ClientList.s"
	@echo "... src/Commander.o"
	@echo "... src/Commander.i"
	@echo "... src/Commander.s"
	@echo "... src/Functions.o"
	@echo "... src/Functions.i"
	@echo "... src/Functions.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Responder.o"
	@echo "... src/Responder.i"
	@echo "... src/Responder.s"
	@echo "... src/TCPServer.o"
	@echo "... src/TCPServer.i"
	@echo "... src/TCPServer.s"
	@echo "... src/TCPSession.o"
	@echo "... src/TCPSession.i"
	@echo "... src/TCPSession.s"
	@echo "... src/UDPServer.o"
	@echo "... src/UDPServer.i"
	@echo "... src/UDPServer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

